enum BusinessFunctionClassification
    @goModel(model: "github.com/DhruvWork/trustready-grc/pkg/coredata.BusinessFunctionClassification") {
    CRITICAL
        @goEnum(
            value: "github.com/DhruvWork/trustready-grc/pkg/coredata.BusinessFunctionClassificationCritical"
        )
    IMPORTANT
        @goEnum(
            value: "github.com/DhruvWork/trustready-grc/pkg/coredata.BusinessFunctionClassificationImportant"
        )
    SECONDARY
        @goEnum(
            value: "github.com/DhruvWork/trustready-grc/pkg/coredata.BusinessFunctionClassificationSecondary"
        )
    STANDARD
        @goEnum(
            value: "github.com/DhruvWork/trustready-grc/pkg/coredata.BusinessFunctionClassificationStandard"
        )
}

enum BusinessFunctionOrderField
    @goModel(model: "github.com/DhruvWork/trustready-grc/pkg/coredata.BusinessFunctionOrderField") {
    CREATED_AT
        @goEnum(
            value: "github.com/DhruvWork/trustready-grc/pkg/coredata.BusinessFunctionOrderFieldCreatedAt"
        )
    REFERENCE_ID
        @goEnum(
            value: "github.com/DhruvWork/trustready-grc/pkg/coredata.BusinessFunctionOrderFieldReferenceID"
        )
    NAME
        @goEnum(
            value: "github.com/DhruvWork/trustready-grc/pkg/coredata.BusinessFunctionOrderFieldName"
        )
    CLASSIFICATION
        @goEnum(
            value: "github.com/DhruvWork/trustready-grc/pkg/coredata.BusinessFunctionOrderFieldClassification"
        )
    MTD_MINUTES
        @goEnum(
            value: "github.com/DhruvWork/trustready-grc/pkg/coredata.BusinessFunctionOrderFieldMTDMinutes"
        )
    RTO_MINUTES
        @goEnum(
            value: "github.com/DhruvWork/trustready-grc/pkg/coredata.BusinessFunctionOrderFieldRTOMinutes"
        )
    RPO_MINUTES
        @goEnum(
            value: "github.com/DhruvWork/trustready-grc/pkg/coredata.BusinessFunctionOrderFieldRPOMinutes"
        )
}

input BusinessFunctionOrder
    @goModel(
        model: "github.com/DhruvWork/trustready-grc/pkg/server/api/console/v1/types.BusinessFunctionOrderBy"
    ) {
    direction: OrderDirection!
    field: BusinessFunctionOrderField!
}

input BusinessFunctionFilter {
    classification: BusinessFunctionClassification
}

type BusinessFunction implements Node {
    id: ID!
    organization: Organization! @goField(forceResolver: true)
    referenceId: String!
    name: String!
    classification: BusinessFunctionClassification!
    mtdMinutes: Int!
    rtoMinutes: Int!
    rpoMinutes: Int!
    impactTolerance: String
    notes: String
    owner: Profile @goField(forceResolver: true)
    assets(
        first: Int
        after: CursorKey
        last: Int
        before: CursorKey
        orderBy: AssetOrder
    ): AssetConnection! @goField(forceResolver: true)
    thirdParties(
        first: Int
        after: CursorKey
        last: Int
        before: CursorKey
        orderBy: ThirdPartyOrder
    ): ThirdPartyConnection! @goField(forceResolver: true)
    createdAt: Datetime!
    updatedAt: Datetime!

    permission(action: String!): Boolean! @goField(forceResolver: true)
}

type BusinessFunctionConnection
    @goModel(
        model: "github.com/DhruvWork/trustready-grc/pkg/server/api/console/v1/types.BusinessFunctionConnection"
    ) {
    totalCount: Int! @goField(forceResolver: true)
    edges: [BusinessFunctionEdge!]!
    pageInfo: PageInfo!
}

type BusinessFunctionEdge {
    cursor: CursorKey!
    node: BusinessFunction!
}

extend type Mutation {
    createBusinessFunction(
        input: CreateBusinessFunctionInput!
    ): CreateBusinessFunctionPayload!
    updateBusinessFunction(
        input: UpdateBusinessFunctionInput!
    ): UpdateBusinessFunctionPayload!
    deleteBusinessFunction(
        input: DeleteBusinessFunctionInput!
    ): DeleteBusinessFunctionPayload!
    publishBusinessFunctionList(
        input: PublishBusinessFunctionListInput!
    ): PublishBusinessFunctionListPayload!
}

input PublishBusinessFunctionListInput {
    organizationId: ID!
    approverIds: [ID!]
    minor: Boolean!
}

type PublishBusinessFunctionListPayload {
    documentEdge: DocumentEdge!
    documentVersionEdge: DocumentVersionEdge!
}

input CreateBusinessFunctionInput {
    organizationId: ID!
    name: String!
    classification: BusinessFunctionClassification!
    mtdMinutes: Int!
    rtoMinutes: Int!
    rpoMinutes: Int!
    impactTolerance: String
    notes: String
    ownerId: ID
    assetIds: [ID!]
    thirdPartyIds: [ID!]
}

input UpdateBusinessFunctionInput {
    id: ID!
    name: String
    classification: BusinessFunctionClassification
    mtdMinutes: Int
    rtoMinutes: Int
    rpoMinutes: Int
    impactTolerance: String @goField(omittable: true)
    notes: String @goField(omittable: true)
    ownerId: ID @goField(omittable: true)
    assetIds: [ID!]
    thirdPartyIds: [ID!]
}

input DeleteBusinessFunctionInput {
    businessFunctionId: ID!
}

type CreateBusinessFunctionPayload {
    businessFunctionEdge: BusinessFunctionEdge!
}

type UpdateBusinessFunctionPayload {
    businessFunction: BusinessFunction!
}

type DeleteBusinessFunctionPayload {
    deletedBusinessFunctionId: ID!
}
