package console_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	"github.com/DhruvWork/trustready-grc/pkg/coredata"
	"github.com/DhruvWork/trustready-grc/pkg/iam"
	"github.com/DhruvWork/trustready-grc/pkg/page"
	"github.com/DhruvWork/trustready-grc/pkg/server/api/console/v1/dataloader"
	"github.com/DhruvWork/trustready-grc/pkg/server/api/console/v1/schema"
	"github.com/DhruvWork/trustready-grc/pkg/server/api/console/v1/types"
	"github.com/DhruvWork/trustready-grc/pkg/server/gqlutils"
	"github.com/DhruvWork/trustready-grc/pkg/trustready"
	"github.com/DhruvWork/trustready-grc/pkg/validator"
	"github.com/vikstrous/dataloadgen"
	"go.gearno.de/kit/log"
)

// Organization is the resolver for the organization field.
func (r *businessFunctionResolver) Organization(ctx context.Context, obj *types.BusinessFunction) (*types.Organization, error) {
	if _, err := r.authorize(ctx, obj.ID, trustready.ActionOrganizationGet); err != nil {
		return nil, err
	}

	loaders := dataloader.FromContext(ctx)

	organization, err := loaders.Organization.Load(ctx, obj.Organization.ID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) || errors.Is(err, dataloadgen.ErrNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot get business function organization", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewOrganization(organization), nil
}

// Owner is the resolver for the owner field.
func (r *businessFunctionResolver) Owner(ctx context.Context, obj *types.BusinessFunction) (*types.Profile, error) {
	if obj.Owner == nil {
		return nil, nil
	}

	if _, err := r.authorize(ctx, obj.Owner.ID, iam.ActionMembershipProfileGet); err != nil {
		return nil, err
	}

	loaders := dataloader.FromContext(ctx)

	owner, err := loaders.Profile.Load(ctx, obj.Owner.ID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) || errors.Is(err, dataloadgen.ErrNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot get business function owner", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return types.NewProfile(owner), nil
}

// Assets is the resolver for the assets field.
func (r *businessFunctionResolver) Assets(ctx context.Context, obj *types.BusinessFunction, first *int, after *page.CursorKey, last *int, before *page.CursorKey, orderBy *types.AssetOrderBy) (*types.AssetConnection, error) {
	scope, err := r.authorize(ctx, obj.ID, trustready.ActionAssetList)
	if err != nil {
		return nil, err
	}

	pageOrderBy := page.OrderBy[coredata.AssetOrderField]{
		Field:     coredata.AssetOrderFieldCreatedAt,
		Direction: page.OrderDirectionDesc,
	}

	if orderBy != nil {
		pageOrderBy = page.OrderBy[coredata.AssetOrderField]{
			Field:     orderBy.Field,
			Direction: orderBy.Direction,
		}
	}

	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	pageResult, err := r.trustready.BusinessFunctions.ListAssets(ctx, scope, obj.ID, cursor)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list business function assets", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewAssetConnection(pageResult, r, obj.ID), nil
}

// ThirdParties is the resolver for the thirdParties field.
func (r *businessFunctionResolver) ThirdParties(ctx context.Context, obj *types.BusinessFunction, first *int, after *page.CursorKey, last *int, before *page.CursorKey, orderBy *types.ThirdPartyOrderBy) (*types.ThirdPartyConnection, error) {
	scope, err := r.authorize(ctx, obj.ID, trustready.ActionThirdPartyList)
	if err != nil {
		return nil, err
	}

	pageOrderBy := page.OrderBy[coredata.ThirdPartyOrderField]{
		Field:     coredata.ThirdPartyOrderFieldCreatedAt,
		Direction: page.OrderDirectionDesc,
	}

	if orderBy != nil {
		pageOrderBy = page.OrderBy[coredata.ThirdPartyOrderField]{
			Field:     orderBy.Field,
			Direction: orderBy.Direction,
		}
	}

	cursor := types.NewCursor(first, after, last, before, pageOrderBy)

	pageResult, err := r.trustready.BusinessFunctions.ListThirdParties(ctx, scope, obj.ID, cursor)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot list business function third parties", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return types.NewThirdPartyConnection(pageResult, r, obj.ID, nil), nil
}

// Permission is the resolver for the permission field.
func (r *businessFunctionResolver) Permission(ctx context.Context, obj *types.BusinessFunction, action string) (bool, error) {
	return r.Resolver.Permission(ctx, obj, action)
}

// TotalCount is the resolver for the totalCount field.
func (r *businessFunctionConnectionResolver) TotalCount(ctx context.Context, obj *types.BusinessFunctionConnection) (int, error) {
	scope, err := r.authorize(ctx, obj.ParentID, trustready.ActionBusinessFunctionList)
	if err != nil {
		return 0, err
	}

	var classification *coredata.BusinessFunctionClassification
	if obj.Filter != nil {
		classification = obj.Filter.Classification
	}

	filter := coredata.NewBusinessFunctionFilter(classification)

	count, err := r.trustready.BusinessFunctions.CountForOrganizationID(ctx, scope, obj.ParentID, filter)
	if err != nil {
		r.logger.ErrorCtx(ctx, "cannot count business functions", log.Error(err))
		return 0, gqlutils.Internal(ctx)
	}

	return count, nil
}

// CreateBusinessFunction is the resolver for the createBusinessFunction field.
func (r *mutationResolver) CreateBusinessFunction(ctx context.Context, input types.CreateBusinessFunctionInput) (*types.CreateBusinessFunctionPayload, error) {
	scope, err := r.authorize(ctx, input.OrganizationID, trustready.ActionBusinessFunctionCreate)
	if err != nil {
		return nil, err
	}

	req := trustready.CreateBusinessFunctionRequest{
		OrganizationID:  input.OrganizationID,
		Name:            input.Name,
		Classification:  input.Classification,
		MTDMinutes:      input.MtdMinutes,
		RTOMinutes:      input.RtoMinutes,
		RPOMinutes:      input.RpoMinutes,
		ImpactTolerance: input.ImpactTolerance,
		Notes:           input.Notes,
		OwnerID:         input.OwnerID,
		AssetIDs:        input.AssetIds,
		ThirdPartyIDs:   input.ThirdPartyIds,
	}

	businessFunction, err := r.trustready.BusinessFunctions.Create(ctx, scope, &req)
	if err != nil {
		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		if errors.Is(err, coredata.ErrResourceAlreadyExists) {
			return nil, gqlutils.Conflictf(ctx, "business function reference already exists")
		}

		r.logger.ErrorCtx(ctx, "cannot create business function", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.CreateBusinessFunctionPayload{
		BusinessFunctionEdge: types.NewBusinessFunctionEdge(businessFunction, coredata.BusinessFunctionOrderFieldCreatedAt),
	}, nil
}

// UpdateBusinessFunction is the resolver for the updateBusinessFunction field.
func (r *mutationResolver) UpdateBusinessFunction(ctx context.Context, input types.UpdateBusinessFunctionInput) (*types.UpdateBusinessFunctionPayload, error) {
	scope, err := r.authorize(ctx, input.ID, trustready.ActionBusinessFunctionUpdate)
	if err != nil {
		return nil, err
	}

	req := trustready.UpdateBusinessFunctionRequest{
		ID:              input.ID,
		Name:            input.Name,
		Classification:  input.Classification,
		MTDMinutes:      input.MtdMinutes,
		RTOMinutes:      input.RtoMinutes,
		RPOMinutes:      input.RpoMinutes,
		ImpactTolerance: gqlutils.UnwrapOmittable(input.ImpactTolerance),
		Notes:           gqlutils.UnwrapOmittable(input.Notes),
		OwnerID:         gqlutils.UnwrapOmittable(input.OwnerID),
	}

	if input.AssetIds != nil {
		req.AssetIDs = &input.AssetIds
	}

	if input.ThirdPartyIds != nil {
		req.ThirdPartyIDs = &input.ThirdPartyIds
	}

	businessFunction, err := r.trustready.BusinessFunctions.Update(ctx, scope, &req)
	if err != nil {
		if validationErrors, ok := errors.AsType[validator.ValidationErrors](err); ok {
			return nil, gqlutils.InvalidValidationErrors(ctx, validationErrors)
		}

		if errors.Is(err, coredata.ErrResourceAlreadyExists) {
			return nil, gqlutils.Conflictf(ctx, "business function reference already exists")
		}

		r.logger.ErrorCtx(ctx, "cannot update business function", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.UpdateBusinessFunctionPayload{
		BusinessFunction: types.NewBusinessFunction(businessFunction),
	}, nil
}

// DeleteBusinessFunction is the resolver for the deleteBusinessFunction field.
func (r *mutationResolver) DeleteBusinessFunction(ctx context.Context, input types.DeleteBusinessFunctionInput) (*types.DeleteBusinessFunctionPayload, error) {
	scope, err := r.authorize(ctx, input.BusinessFunctionID, trustready.ActionBusinessFunctionDelete)
	if err != nil {
		return nil, err
	}

	if err := r.trustready.BusinessFunctions.Delete(ctx, scope, input.BusinessFunctionID); err != nil {
		r.logger.ErrorCtx(ctx, "cannot delete business function", log.Error(err))
		return nil, gqlutils.Internal(ctx)
	}

	return &types.DeleteBusinessFunctionPayload{
		DeletedBusinessFunctionID: input.BusinessFunctionID,
	}, nil
}

// PublishBusinessFunctionList is the resolver for the publishBusinessFunctionList field.
func (r *mutationResolver) PublishBusinessFunctionList(ctx context.Context, input types.PublishBusinessFunctionListInput) (*types.PublishBusinessFunctionListPayload, error) {
	scope, err := r.authorize(ctx, input.OrganizationID, trustready.ActionBusinessFunctionPublish)
	if err != nil {
		return nil, err
	}

	document, documentVersion, err := r.trustready.GeneratedDocuments.PublishBusinessFunctionList(ctx, scope, input.OrganizationID, input.ApproverIds, input.Minor)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceAlreadyExists) {
			return nil, gqlutils.Conflict(ctx, err)
		}

		r.logger.ErrorCtx(ctx, "cannot publish business function list", log.Error(err))

		return nil, gqlutils.Internal(ctx)
	}

	return &types.PublishBusinessFunctionListPayload{
		DocumentEdge:        types.NewDocumentEdge(document, coredata.DocumentOrderFieldCreatedAt),
		DocumentVersionEdge: types.NewDocumentVersionEdge(documentVersion, coredata.DocumentVersionOrderFieldCreatedAt),
	}, nil
}

// BusinessFunction returns schema.BusinessFunctionResolver implementation.
func (r *Resolver) BusinessFunction() schema.BusinessFunctionResolver {
	return &businessFunctionResolver{r}
}

// BusinessFunctionConnection returns schema.BusinessFunctionConnectionResolver implementation.
func (r *Resolver) BusinessFunctionConnection() schema.BusinessFunctionConnectionResolver {
	return &businessFunctionConnectionResolver{r}
}

type (
	businessFunctionResolver           struct{ *Resolver }
	businessFunctionConnectionResolver struct{ *Resolver }
)
