package console_v1

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"

	"github.com/DhruvWork/trustready-grc/pkg/coredata"
	"github.com/DhruvWork/trustready-grc/pkg/probot/identitybinding"
	"github.com/DhruvWork/trustready-grc/pkg/server/api/authn"
	"github.com/DhruvWork/trustready-grc/pkg/server/api/console/v1/types"
	"github.com/DhruvWork/trustready-grc/pkg/server/gqlutils"
	"go.gearno.de/kit/log"
)

// ConfirmTrustReadytIdentityBinding is the resolver for the confirmTrustReadytIdentityBinding field.
func (r *mutationResolver) ConfirmTrustReadytIdentityBinding(ctx context.Context, input types.ConfirmTrustReadytIdentityBindingInput) (*types.ConfirmTrustReadytIdentityBindingPayload, error) {
	if r.trustreadytIdentityBindings == nil {
		return nil, gqlutils.Internal(ctx)
	}

	identity := authn.IdentityFromContext(ctx)
	if identity == nil {
		return nil, gqlutils.Internal(ctx)
	}

	binding, err := r.trustreadytIdentityBindings.Confirm(
		ctx,
		identity.ID,
		input.Token,
	)
	if err != nil {
		switch {
		case errors.Is(err, identitybinding.ErrAlreadyBound),
			errors.Is(err, identitybinding.ErrChallengeAlreadyUsed):
			return nil, gqlutils.Conflict(ctx, err)
		case errors.Is(err, identitybinding.ErrChallengeExpired),
			errors.Is(err, coredata.ErrResourceNotFound):
			return nil, gqlutils.Invalid(ctx, err)
		default:
			r.logger.ErrorCtx(
				ctx,
				"cannot confirm Probot identity binding",
				log.Error(err),
			)

			return nil, gqlutils.Internal(ctx)
		}
	}

	return &types.ConfirmTrustReadytIdentityBindingPayload{
		TrustReadytIdentityBinding: types.NewTrustReadytIdentityBinding(binding),
		Viewer:                currentViewer(ctx),
	}, nil
}

// DeleteTrustReadytIdentityBinding is the resolver for the deleteTrustReadytIdentityBinding field.
func (r *mutationResolver) DeleteTrustReadytIdentityBinding(ctx context.Context, input types.DeleteTrustReadytIdentityBindingInput) (*types.DeleteTrustReadytIdentityBindingPayload, error) {
	if r.trustreadytIdentityBindings == nil {
		return nil, gqlutils.Internal(ctx)
	}

	identity := authn.IdentityFromContext(ctx)
	if identity == nil {
		return nil, gqlutils.Internal(ctx)
	}

	err := r.trustreadytIdentityBindings.Delete(ctx, identity.ID, input.ID)
	if err != nil {
		if errors.Is(err, coredata.ErrResourceNotFound) {
			return nil, gqlutils.NotFound(ctx, err)
		}

		r.logger.ErrorCtx(
			ctx,
			"cannot delete Probot identity binding",
			log.Error(err),
		)

		return nil, gqlutils.Internal(ctx)
	}

	return &types.DeleteTrustReadytIdentityBindingPayload{
		TrustReadytIdentityBindingID: input.ID,
		Viewer:                  currentViewer(ctx),
	}, nil
}
