type Invitation implements Node {
  id: ID!
  expiresAt: Datetime!
  acceptedAt: Datetime
  createdAt: Datetime!
  status: InvitationStatus!

  permission(action: String!): Boolean!
    @goField(forceResolver: true)
    @authentication(required: PRESENT)
}

enum InvitationStatus
  @goModel(model: "github.com/DhruvWork/trustready-grc/pkg/coredata.InvitationStatus") {
  PENDING
    @goEnum(value: "github.com/DhruvWork/trustready-grc/pkg/coredata.InvitationStatusPending")
  ACCEPTED
    @goEnum(value: "github.com/DhruvWork/trustready-grc/pkg/coredata.InvitationStatusAccepted")
  EXPIRED
    @goEnum(value: "github.com/DhruvWork/trustready-grc/pkg/coredata.InvitationStatusExpired")
}

enum InvitationOrderField
  @goModel(model: "github.com/DhruvWork/trustready-grc/pkg/coredata.InvitationOrderField") {
  CREATED_AT
    @goEnum(
      value: "github.com/DhruvWork/trustready-grc/pkg/coredata.InvitationOrderFieldCreatedAt"
    )
}

input InvitationOrder
  @goModel(
    model: "github.com/DhruvWork/trustready-grc/pkg/server/api/connect/v1/types.InvitationOrderBy"
  ) {
  direction: OrderDirection!
  field: InvitationOrderField!
}

type InvitationConnection
  @goModel(
    model: "github.com/DhruvWork/trustready-grc/pkg/server/api/connect/v1/types.InvitationConnection"
  ) {
  edges: [InvitationEdge!]!
  pageInfo: PageInfo!
}

type InvitationEdge {
  node: Invitation!
  cursor: CursorKey!
}

extend type Mutation {
  inviteUser(input: InviteUserInput!): InviteUserPayload
    @authentication(required: PRESENT)
}

input InviteUserInput {
  organizationId: ID!
  profileId: ID!
}

type InviteUserPayload {
  invitationEdge: InvitationEdge!
}
